### ISSUE TITLE
Cannot read property 'export' of undefined

### ISSUE THREAD

**Issue by RoySijnesael** [themeteorchef/handling-webhooks#1]
I keep getting this error when I try to start the app. I seriously have no idea what I should do.

`import { stripeHandler } from './providers/stripe';

let module;

const providers = {
  stripe: stripeHandler,
};

const handler = ({ provider, request }, promise) => {
  try {
    module = promise;
    const targetProvider = providers[provider];
    if (targetProvider) targetProvider({ body: request.body });
    module.resolve('Webhook received!');
  } catch (exception) {
    module.reject(`[handleWebhook.handler] ${exception}`);
  }
};

export const handleWebhook = (options) =>
new Promise((resolve, reject) =>
handler(options, { resolve, reject }));`

**Comment by cleverbeagle** [comment]
Hi @RoySijnesael what is the error? This is just the contents of one of the files in the example.

**Comment by RoySijnesael** [comment]
Hi @cleverbeagle, 
The error I keep getting is also in the title, but here is the output from my terminal:

```
W20170906-18:11:53.569(2)? (STDERR) TypeError: Cannot read property 'export' of undefined
W20170906-18:11:53.570(2)? (STDERR)     at meteorInstall.imports.api.public.handle-webhook.js (imports/api/public/handle-webhook.js:1:22)
W20170906-18:11:53.570(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170906-18:11:53.571(2)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170906-18:11:53.571(2)? (STDERR)     at meteorInstall.imports.api.public.api.js (imports/api/public/api.js:1:199)
W20170906-18:11:53.572(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170906-18:11:53.573(2)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170906-18:11:53.573(2)? (STDERR)     at meteorInstall.server.main.js (server/main.js:1:183)
W20170906-18:11:53.574(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170906-18:11:53.574(2)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170906-18:11:53.575(2)? (STDERR)     at /Users/roysijnesael/GitHub/viatim-statusboard/.meteor/local/build/programs/server/app/app.js:212:1
```

**Comment by cleverbeagle** [comment]
Ah. This is a gotcha with the latest versions of Meteor. You'll want to update the `module` variable in that file to be `action`. So, `let action;` instead of `let module`; and then update all references to `module` to be `action`. This was a surprise change in Meteor ~1.4.1 that started to block the keyword `module` :/

**Comment by RoySijnesael** [comment]
Oh wow! I always feel so stupid when it's such a small thing.. Oh well, thanks man, I've got it working, you're a real hero! :)
